### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by DanielRuf** [artemisbot/libyara-wasm#1]
It seems the index.html file was removed in https://github.com/mattnotmitt/libyara-wasm/commit/bb447598d5f27bb73ce374cf5de987ba17c843ba

It would be helpful to have some examples and also unit tests.

**Comment by mattnotmitt** [comment]
Hi @DanielRuf, this is an MVP for implementing basic Yara functionality into gchq/CyberChef. I don't really have the time atm to flesh out this library but I'll see what documentation and examples I can spin out when I can get around to it.

**Comment by mattnotmitt** [comment]
Meant to say, have a look at [this file](https://github.com/gchq/CyberChef/blob/master/src/core/operations/YARARules.mjs) if you want to take a look at an example before I get around to writing some.
