### ISSUE TITLE
Add console module

### ISSUE THREAD

**Issue by malvidin** [artemisbot/libyara-wasm#6]
Please update to 4.2, and include the console module to enhance rule debugging.

**Comment by mattnotmitt** [comment]
Just published v1.2.0 which updates Yara to 4.2.3. Right now the console module is compiled in but I'm not sure how you'd want to handle it. I'd receive it in a callback which I could pipe straight to std::cout (which appears in the JS console) or it could be returned in the YaraCC class.

**Comment by malvidin** [comment]
I would appreciate output in CyberChef similar to what the YARA CLI and Python API provide.  If it was in the JS console, I don't know if most users would find it, and some users might be part of organizations that block browser devtools.

```yara
import "console" 
rule a 
{
  strings: 
    $s=" " 
  condition: 
    $s and console.log("log rule a")
} 
rule b 
{
  strings: 
    $s=" " 
  condition: 
    $s and console.hex("log rule b: int8(0)=", int8(0))
}
```

Using the rules above and the input `CyberChef YARA`:
```
log rule a
log rule b: int8(0)=0x59
Input matches rule "a" 0 time.
Input matches rule "b" 0 time.
```

Or showing each match like CyberChef Unzip file lists:
```
Warning on line 5: string "$s" may slow down scanning'
Warning on line 12: string "$s" may slow down scanning'
log rule a
log rule b: int8(0)=0x43
2 match(es) found:
Rule "a"                        matches (1 time):
  Pos 9, length 1, identifier $s, data: " "
Rule "b"                        matches (1 time):
  Pos 9, length 1, identifier $s, data: " "
```

**Comment by mattnotmitt** [comment]
Great, thanks for the detailed request. Will work on this today.

**Comment by mattnotmitt** [comment]
Released version v1.2.1 with support for printing console messages. MR is in for support in CyberChef.

**Comment by malvidin** [comment]
Should other modules be added? Some, like Cuckoo, appear out of scope for CyberChef.  I don't know the impact that adding Time/Math vs. PE/ELF would have on the CyberChef bundle or its performance.  If appropriate, I can add an issue for other modules.

**Comment by mattnotmitt** [comment]
I think all four of those modules are already included (or at least, they don't fail to compile on me)! The only ones I don't have in at the moment are `cuckoo` and `magic`, the first because nobody's asked me to and the second because getting libmagic to compile was such a pain. I've never tested `pe` or `elf` though, mainly because I'm not a malware researcher or anything of the type and have absolutely no idea how I'd use them :) 

EDIT: Just noticed the `dotnet` module too. I don't explicitly compile it in but it appears to have snuck in and does seem to work fine in browser using one of the test cases from the main yara repository.

**Comment by malvidin** [comment]
That is really great to hear. I apologize for not checking in this build before asking.

I don't know many who use the `magic` module, and I still don't know how `cuckoo` would work in CyberChef.

**Comment by mattnotmitt** [comment]
No worries! I didn't even know they were in there. If there's anything else you want in CyberChef and want to check the feasibility before opening an issue you can email me at me[at]mitt.dev or catch me on twitter with the same username as GitHub.
